spring:
  datasource:
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/grocery-app
    username: integrity
    password: password
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
